config/routes.rb
Rails.application.routes.draw do
	resources :recipes do
		collection do
			get 'add_to_favs'
			get 'search_for_deals'
			get 'search_for_recipes'
			get 'populate_db'
		end
	end

	resources :users do
		collection do
			get 'delete_from_favs'
		end
	end

	root 'landing#index'
	get '/signup'  => 'users#new' 
	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false }
	serialize :categories
	serialize :ingredients
	serialize :directions
	has_and_belongs_to_many :users

	def self.search(search)
		if search
			where(['name LIKE ?', "%#{search}%"])
		else
			where(['name LIKE ?', ""])
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
	include Gravtastic
	validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }
	has_and_belongs_to_many :recipes
	has_secure_password
	gravtastic

	def admin?
		return self.role == 'admin'
	end

	def premium?
		return self.role == 'premium'
	end
end

app/controllers/application_controller.rb
# frozen-string-literal: true

# The Application controller is part of the MVC framework for the app
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_admin
    if current_user
      redirect_to '/recipes' unless current_user.admin?
    else
      redirect_to '/recipes'
    end
  end
end

app/controllers/landing_controller.rb
# frozen-string-literal: true

# The Landing controller is part of the MVC framework for the landing page
class LandingController < ApplicationController
  def index
    @recipes = Recipe.order('RAND()').all[0..9] # randomize recipes on main page
    puts 'OGH2EOIHGOEHGOEHWOIGHWEOIGHEOWGHEWIOGHWEHGIEWOHGOWGHWEIGWIHOGWEG'
    puts @recipes
  end
end

app/controllers/recipes_controller.rb
# frozen-string-literal: true

# The LandingController is part of the MVC framework for the recipes page
class RecipesController < ApplicationController
  before_action :require_admin, only: %i[edit destroy]
  def index
    @recipes = Recipe.order('RAND()').all # randomize recipes shown on main page!
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = current_user ? current_user : nil
  end

  def edit
    @recipes = Recipe.all
  end

  def destroy
    Recipe.destroy(params[:id])
    flash.notice = 'The recipe was deleted from the database.'
    redirect_to recipes_path
  end

  def add_to_favs
    recipe = Recipe.find(params[:recipe_id])
    user = User.find(params[:user_id])
    user.recipes << recipe unless user.recipes.include?(recipe)
    redirect_to recipe_path(recipe)
  end

  def search_for_recipes
    @query = params[:search_param]
    @recipes = Recipe.all.search(@query)
  end

  def search_for_deals
    options = Selenium::WebDriver::Chrome::Options.new
    chrome_bin = ENV.fetch('GOOGLE_CHROME_SHIM', nil)
    unless chrome_bin
      Selenium::WebDriver::Chrome.driver_path = '/Users/alexxie/Documents/GitHub/easy-recipeasy/bin/chromedriver'
      options.add_argument('--headless')
    end
    options.binary = chrome_bin if chrome_bin
    driver = Selenium::WebDriver.for :chrome, options: options
    search_url = "https://www.flipp.com/search?q=#{params[:item]}"
    driver.navigate.to search_url
    sleep 3 # allow javascript to load in

    parse_page = Nokogiri::HTML(driver.page_source)

    @img_links = []

    parse_page.css('.item-container').each do |finding|
      @img_links << [finding.css('a').attr('href').to_s.split('?')[0][15..-1],
                     "https://www.flipp.com#{finding.css('a').attr('href')}",
                     finding.css('.clipping').attr('src')]
    end
  end

  def populate_db
    puts 'egohwoqhoghoHOhgoHGOIEWhoghoHEIGhogehwhGO'
    puts params[:requested_query]
    app_key = 'a8c2f79449116a1aaae82fa3a64ea49c' # specific to this application
    app_id = '01d44b0a' # specific to this application
    query = params[:requested_query]
    api_url = "https://api.edamam.com/search?q=#{query}&app_id=#{app_id}&app_key=#{app_key}"
    raw_response = HTTParty.get(api_url)
    # puts raw_response
    # check error messages here
    parsed_recipes = JSON.parse(raw_response.body)
    puts parsed_recipes.length
    parsed_recipes['hits'].each do |r|
      new_r = Recipe.new
      new_r.name = r['recipe']['label']
      new_r.likes = 0
      new_r.servings = r['recipe']['yield']
      new_r.categories = (r['recipe'].key?('dietLabels') && r['recipe'].key?('healthLabels')) ? r['recipe']['dietLabels'] + r['recipe']['healthLabels'] : []
      all_ingredients = []
      r['recipe']['ingredients'].each do |ing|
        puts ing['text']
        all_ingredients << ing['text']
      end
      new_r.ingredients = all_ingredients
      new_r.img_url = r['recipe']['image']
      new_r.source = r['recipe'].key?('source') ? r['recipe']['source'] : 'Unknown'
      new_r.orig_url = r['recipe'].key?('url') ? r['recipe']['url'] : 'Unknown'
      new_r.calories = r['recipe']['calories']
      if new_r.save
        puts "SAVED #{new_r.name}"
      else
        puts "Error saving #{new_r.name}: #{new_r.errors.messages}"
      end
    end
    redirect_to recipes_path
  end
end

app/controllers/sessions_controller.rb
# frozen-string-literal: true

# The Sessions controller is part of the MVC framework for sessions
class SessionsController < ApplicationController
  def new; end

  def create
    puts 'NEW SESSION ATTEMPT------------------------------------'
    puts params[:session][:email]
    @user = User.find_by email: params[:session][:email]
    puts params[:session][:password]
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/recipes'
    else
      flash.notice = 'Your login was invalid. Please try again.'
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/recipes'
  end
end

app/controllers/users_controller.rb
# frozen-string-literal: true

# The Users controller is part of the MVC framework for user pages
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :require_admin, only: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])
    flash.notice = 'The user was removed.'
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  def create
    @user = User.new(user_params)
    @user.role = 'standard'
    @user.errors.each do |_attribute, message|
      puts message
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/users'
    else
      flash.notice = 'Your signup credentials were invalid. Try it again! Error: ' + @user.errors.messages.to_s
      redirect_to '/signup'
    end
  end

  def delete_from_favs
    user = User.find(params[:user_id])
    recipe = user.recipes.find(params[:recipe_id])
    user.recipes.delete(recipe) if recipe
    redirect_to recipe_path(recipe)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :bio, :password,
                                 :role, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
	<!-- Description, Keywords and Author -->
	<title>Easy Recipeasy</title>
	<meta desc="Easy Recipeasy is a recipe web app that makes it easy for you to find new recipes and cook them! It has features like custom login and profiles to save recipes you like, and Flipp integration so that you can find the best deals on ingredients.">
	<meta name="author" content="Alex Yizhe Xie">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<meta charset="utf-8">
	
	<!-- style -->
	<%= stylesheet_link_tag "css/user-page-style.css" %> 
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap-grid.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap-reboot.min.css" %>
	<%= stylesheet_link_tag "css/user-dropdown-style.css" %>
	<%= stylesheet_link_tag "css/additional-user-style.css", :type => "text/css" %>
	<%= stylesheet_link_tag "css/style.css" %> 
	<%= stylesheet_link_tag "css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "css/responsive.css" %>
	<%= stylesheet_link_tag "css/font-awesome.min.css" %>
	<%= stylesheet_link_tag "css/effects/set2.css" %>
	<%= stylesheet_link_tag "css/effects/normalize.css"  %>
	<%= stylesheet_link_tag "css/effects/component.css" %>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114911192-2"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-114911192-2');
	</script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>


<body style="background-color: #ffffff">
	<main role="main-home-wrapper" class="container" style="margin-top: 125px">
		<!-- Left Row -->
		<section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 grid" style="background-color: #ffffff">
			<ul class="grid-lod effect-2" id="grid">
				<li>
					<figure style="background-color: #e84d49">
						<%=image_tag("logo-main-landing.png", style: "opacity: 1;background-color: #ffffff; margin-top:-30px") %>
						<h2 style="margin: 20px">

							<% if current_user %> 
							<span>Welcome back, <%= current_user.name %></span>!
							<% else %>
							<%= link_to '<span style="font-size: 3rem" >Log in</span>'.html_safe, login_path, style: "color: inherit; text-decoration: inherit; display: inline" %> or <%= link_to '<span style="font-size: 3rem" >sign up</span>'.html_safe, signup_path, style: "color: inherit; text-decoration: inherit; display: inline" %> for more!
							<% end %>
						</h2>

					</figure>
				</li>
				<li>
					<figure style="background-color: #e84d49; margin-left: 40px; margin-top: -5%">
						<h2 style="margin: 20px; font-size: 2rem; letter-spacing: 1.2px">Check out these new flavours, just for you:</h2>
					</figure>
				</li>

				<% @recipes[0..4]&.each do |recipe| %>
				<li>
					<figure class="effect-oscar">
						<% food_img = recipe.img_url ? recipe.img_url : "home-images/image-steak.jpg" %>
						<%=image_tag(food_img, class: 'img-responsive', style: "opacity: 0.75") %>
						<figcaption>
							<h2 style="margin: 0px"><span><%= recipe.name %></span></h2>
							<p style="margin-top: 10px">
								<%= recipe.desc %><br><br>
								<i class="fas fa-fire"></i> <%= recipe.calories %>&nbsp;&nbsp;
								<i class="fas fa-utensils"></i> <%= recipe.servings %>  &nbsp;&nbsp;
								<i class="fas fa-clock"></i></i> <%= recipe.cooktime %>
							</p>
							<%= link_to recipe.name, recipe_path(recipe) %>
						</figcaption>
					</figure>
				</li>
				<% end %>
			</ul>
		</section>

		<!-- Right Row -->
		<section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 grid" style="background-color: #ffffff">
			<ul class="grid-lod effect-2" id="grid">
				<% @recipes[5..9]&.each do |recipe| %>
				<li>
					<figure class="effect-oscar">
						<% food_img = recipe.img_url ? recipe.img_url : "home-images/image-steak.jpg" %>
						<%=image_tag(food_img, class: 'img-responsive', style: "opacity: 0.75") %>
						<figcaption>
							<h2 style="margin: 0px"><span><%= recipe.name %></span></h2>
							<p style="margin-top: 10px">
								<%= recipe.desc %><br><br>
								<i class="fas fa-fire"></i> <%= recipe.calories %>&nbsp;&nbsp;
								<i class="fas fa-utensils"></i> <%= recipe.servings %>  &nbsp;&nbsp;
								<i class="fas fa-clock"></i></i> <%= recipe.cooktime %>
							</p>
							<%= link_to recipe.name, recipe_path(recipe) %>
						</figcaption>
					</figure>
				</li>
				<% end %>
			</ul>
		</section>
		<div class="clearfix"></div>
	</div>
</main>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<%= javascript_include_tag "js/jquery.min.js"  %>
<%= javascript_include_tag "js/nav.js"  %>
<%= javascript_include_tag "js/custom.js"  %>
<%= javascript_include_tag "js/bootstrap.min.js"  %>
<%= javascript_include_tag "js/effects/masonry.pkgd.min.js"  %>
<%= javascript_include_tag "js/effects/imagesloaded.js"  %>
<%= javascript_include_tag "js/effects/classie.js"  %>
<%= javascript_include_tag "js/effects/AnimOnScroll.js"  %>
<%= javascript_include_tag "js/effects/modernizr.custom.js"  %>
<%= javascript_include_tag "js/html5shiv.js"  %>
<%= javascript_include_tag "user-js/jquery.min.js"  %>
<%= javascript_include_tag "user-js/bootstrap.min.js"  %>
<%= javascript_include_tag "user-js/script.js"  %>
<%= javascript_include_tag "user-js/dropdown-script.min.js"  %>
</body>

</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
	<meta name="description" content="Recipe Page">
	<title><%= @recipe.name%></title>

	<%= stylesheet_link_tag "css/recipe-page-style.css" %> 
	<%= stylesheet_link_tag "css/bootstrap-recipe-css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-recipe-css/bootstrap-grid.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-recipe-css/bootstrap-reboot.min.css" %>
	<%= stylesheet_link_tag "css/additional-recipe-style.css", :type => "text/css" %>
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>
<body>
	<section class="counters1 counters cid-qKxEBp95ZB" id="counters1-t" style="margin-top: 40px">
		<div class="container">   
			<div class="col-md-12">
				<div class="media-container-row">
					<div class="mbr-figure" style="width: 100%%; align-self: auto; padding-top:1.5rem!important; margin-left: 1rem!important">
						<% food_img = @recipe.img_url ? @recipe.img_url : "home-images/image-steak.jpg" %>
						<%= image_tag(food_img, style: 'max-width: 1000px; max-height: 900px') %>
					</div>
					<div class=" align-left aside-content" style="max-width: 50%">
						<h2 class="mbr-title pt-2 mbr-fonts-style display-2" style="font-size: 5rem">
							<%= @recipe.name %>
							<%= 
							if @user
								if @user.recipes.exists?(@recipe.id)
									link_to '<i class="fas fa-heart"></i></i>'.html_safe, delete_from_favs_users_path(user_id:@user.id, recipe_id: @recipe.id), class: "fav_recipe_true", style: "font-size:0.7em", data: { confirm: "Delete from your favourites?" }
								else
									link_to '<i class="far fa-heart"></i>'.html_safe,  add_to_favs_recipes_path(user_id:@user.id, recipe_id: @recipe.id), class: "fav_recipe_false", style: "font-size:0.7em"
								end
							else
								link_to '<i class="far fa-heart"></i>'.html_safe, login_path, class: "fav_recipe_false", style: "font-size:0.7em"
							end
							%>
							<span style="font-size:0.7em; color: #fb5353"><%= @recipe.users.size.to_s %></span>
						</h2>
						<div style="display:table">
							<div style="display: table-cell; min-width: 100px">
								<h3 class="count pt-3 pb-3 mbr-fonts-style display-2">
									<%= @recipe.calories %>
								</h3>
								<h4 class="mbr-content-title mbr mbr-fonts-style display-7" style="font-size:1.5rem">
									Calories
								</h4>
							</div>
							<div style="display: table-cell; min-width: 100px">
								<h3 class="count pt-3 pb-3 mbr-fonts-style display-2" >
									<%= @recipe.servings %>
								</h3>
								<h4 class="mbr-content-title mbr mbr-fonts-style display-7" style="font-size:1.5rem">
									Servings
								</h4>
							</div>
							<div style="display: table-cell; min-width: 100px">
								<h3 class="count pt-3 pb-3 mbr-fonts-style display-2">
									<%= @recipe.cooktime %>
								</h3>
								<h4 class="mbr-content-title mbr mbr-fonts-style display-7" style="font-size:1.5rem">
									Minutes to Make
								</h4>
							</div>
						</div>
						<div class="mbr-section-text">
							<h4 class="mbr-title pt-2 mbr-fonts-style display-3" style="font-size:3rem; margin-top: 20px">
								Description
							</h4>
							<p class="mbr-text mb-5 pt-1 mbr mbr-fonts-style display-5" style="font-size:1.5rem; line-height: 1.4">
								<%= @recipe.desc %>
							</p>
							<% if @recipe.ingredients %>
							<h4 class="mbr-title pt-2 mbr-fonts-style display-3" style="font-size:3rem">
								Ingredients
							</h4>
							<ul style="columns: 3; -webkit-columns: 3; -moz-columns:3">
								<% @recipe.ingredients.each do |ingr| %>
								<li style="margin-left: 15px; font-size:1.5rem"><%= link_to ingr.capitalize, search_for_deals_recipes_path(item:ingr) %></li>
								<% end %> 
							</ul>
							<% end %>
							
							<% if @recipe.directions %>
							<h4 class="mbr-title pt-0 mbr-fonts-style display-3" style="margin-top:10px; font-size: 3rem">
								Directions
							</h4>
							<ol>
								<% @recipe.directions.each do |dir| %>
								<li style="margin-left: 15px; font-size:1.5rem"><%= dir %></li>
								<% end %> 
							</ol>
							<% end %>
							<% if @recipe.categories %>
								<h4 class="mbr-title pt-0 mbr-fonts-style display-5" style="font-size:2rem; display: inline">
									Categories
								</h4>
								<% @recipe.categories.each do |cat| %>
								<span style="font-size:1.5rem">.<%= cat %> </span>
								<% end %>
							<% end %>

							<br>
							<br>
						
							<% if current_user and current_user.admin? %>
								<h4 class="mbr-title pt-0 mbr-fonts-style display-5" style="font-size:1.5rem; display: inline">
									Administrator Options
								</h4>
								<span style="font-size:1.5rem">.<%= link_to "delete", recipe_path(@recipe), method: :delete %></span>
							<% end %>
							
							<span style="font-size:2rem">
								<br>
								<br>
								<br>
								<%= link_to "<< Back to Home", '/' %>
							</span>
						</div>
					</div>
				</div>
			</div> 
		</div>          
	</section>

	<%= javascript_include_tag "recipe-js/jquery.min.js"  %>
	<%= javascript_include_tag "recipe-js/bootstrap.min.js"  %>
	<%= javascript_include_tag "recipe-js/jquery.viewportchecker.js"  %>
	<%= javascript_include_tag "recipe-js/script.js"  %>
</body>
</html>

app/views/shared/_footer.html.erb
  <footer role="footer" style="padding-top: 10px; padding-bottom: 10px">
  	<p class="copy-right">
  	&copy; 2018  Alex Xie </p>
  </footer>

app/views/shared/_nav-bar.html.erb
<section class="menu cid-qKy4oqvKRV" once="menu" id="menu2-h">
	<nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm" style="-webkit-box-shadow: 0px 1px 4px 0px rgba(201,201,201,1);
-moz-box-shadow: 0px 1px 4px 0px rgba(201,201,201,1);
box-shadow: 0px 1px 4px 0px rgba(201,201,201,1)">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<div class="hamburger">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
	</button>
	<div class="menu-logo">
		<div class="navbar-brand">
			<span class="navbar-logo">
				<a href="https://mobirise.com">
					<%= link_to image_tag("rsz_logo.png", id:"navbar-logo"), '/' %>
				</a>
			</span>

		</div>
	</div>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
			<li class="nav-item">
				<a class="nav-link link text-black display-4" href="/recipes">
					<i class="fas fa-list-alt" style="font-size:40px; margin-top:5px; color: #e84d49"></i>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link link text-black display-4" href="#">
					<% if current_user %>
					<%= link_to image_tag(current_user.gravatar_url, :style => "max-width: 40px; max-height: 40px; border-width: 4px; border-color: #e84d49; border-style:solid; border-radius:4px; margin-top:-10px", id: "p"),  user_path(current_user), class: "menu-link" %>
					<% end %>
				</a>
			</li>
		</ul>
		<% unless current_user %>
		<div class="navbar-buttons mbr-section-btn">
			<%= link_to '<span class="btn-icon mbri-mobile mbr-iconfont mbr-iconfont-btn"></span>Log In'.html_safe, login_path, class: "btn btn-sm btn-primary display-4" %>
			<%= link_to '<span class="btn-icon mbri-mobile mbr-iconfont mbr-iconfont-btn"></span>Sign Up'.html_safe, signup_path, class: "btn btn-sm btn-primary display-4" %>
		</div>
		<% end %>
	</div>
</nav>
</section>

app/views/users/show.html.erb
<!DOCTYPE html>
<html >
<head>
	<meta charset="UTF-8">
	<title><%= current_user.name %> - Profile</title>
	<%= stylesheet_link_tag "css/user-page-style.css" %> 
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap-grid.min.css" %>
	<%= stylesheet_link_tag "css/bootstrap-user-css/bootstrap-reboot.min.css" %>
	<%= stylesheet_link_tag "css/user-dropdown-style.css" %>
	<%= stylesheet_link_tag "css/additional-user-style.css", :type => "text/css" %>
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>
<body style="color: #e84d49">
	<% if current_user and current_user.admin? %>
		<p style="margin-top:100px">Administrator Mode</p>
		<h4>Populate Database: </h4>
		<%= form_tag(populate_db_recipes_path, method: :get, id: "populate-field-admin") do %>
			<%= text_field_tag :requested_query %>
			<% submit_tag "Populate Database" %>
		<% end %>
		<input type="submit" value="Populate" form="populate-field-admin">
		<br>
		<%= link_to "All Users", users_path %>
	<% end %>
	<section class="engine"><a href="#""></a></section><section class="carousel slide testimonials-slider cid-qKy4q5kW1B" id="testimonials-slider1-i">
		<div class="container text-center">
			<h2 class="pb-5 mbr-fonts-style display-2" style="padding-top:40px">
				Your Profile
			</h2>
			<div class="user col-md-8" style="padding-left: 35%">
				<div class="user_image">
					<%= image_tag @user.gravatar_url %>
				</div>
				<div class="user_text pb-3">
					<h2 style="font-size: 3rem">
						<%= @user.name %>
						<%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_user_path(@user) %>
						<%= link_to '<i class="fas fa-sign-out-alt"></i>'.html_safe, logout_path, method: :delete%> <br>
					</h2>
					<p class="mbr-fonts-style display-7">
						<%- @user.bio %>
					</p>
				</div>
				<div style="margin-bottom: 20px">
					<div style="float:left">
						<div class="user_name mbr-bold pb-2 mbr-fonts-style display-5">
							Role:
						</div>
						<div class="user_desk mbr-light mbr-fonts-style display-5">
							<%= @user.role.to_s.capitalize %>
						</div>
					</div>
					<div style="float:right">
						<div class="user_name mbr-bold pb-2 mbr-fonts-style display-5">
							User since:
						</div>
						<div class="user_desk mbr-light mbr-fonts-style display-5">
							<%= @user.created_at %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="features17 cid-qKy4yyWHqe" id="features17-k">
		<h1 style="padding-left:75px">Favourites</h1>
		<div class="container-fluid">
			<div class="media-container-row">
				<% @user.recipes.each do |recipe| %>
				<div class="card p-3 col-12 col-md-6 col-lg-2">
					<div class="card-wrapper">
						<div class="card-img">
							<% food_img = recipe.img_url ? recipe.img_url : "home-images/image-steak.jpg" %>
							<%=image_tag(food_img, class: 'img-responsive') %>
						</div>
						<div class="card-box">
							<h4 class="card-title pb-3 mbr-fonts-style display-7">
								<%= link_to recipe.name, recipe_path(recipe) %>
							</h4>
							<p class="mbr-text mbr-fonts-style display-7">
								<%= link_to "X Delete", delete_from_favs_users_path(user_id:current_user.id, recipe_id:recipe.id), data: { confirm: "Are you sure?" }%>
							</p>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<%= link_to "<< Back to Home", "/" , style: "margin-left: 75px" %>
	</section>


	<%= javascript_include_tag "user-js/jquery.min.js"  %>
	<%= javascript_include_tag "user-js/bootstrap.min.js"  %>
	<%= javascript_include_tag "user-js/script.js"  %>
	<%= javascript_include_tag "user-js/dropdown-script.min.js"  %>


</body>
</html>